### ISSUE TITLE
Inflated page views when speculative pre-rendering is enabled

### ISSUE THREAD

**Issue by ramboz** [adobe/aem-lib#101]
### Expected Behaviour

When speculative prerendering is used on a site, we should only track page views and trigger RUM events once the page is actually activated (i.e. navigated to).

### Actual Behaviour

From a recent test we did with petplace, it looks like RUM events are tracked for all prerendered pages as we saw a noticeable increase of page views that deviated from the norm right after enabling the feature.
See https://cq-dev.slack.com/archives/C07198KKQ07/p1728084960712759

#### Steps to Reproduce

1. Enable speculative prerendering on a site.
2. Let it run for a few hours
3. Check RUM Explorer metrics

#### Platform and Version

Any

#### Sample Code that illustrates the problem

Add this to your `head.html`:
```html
<script type="speculationrules">
    {
        "prerender": [{
            "where": {
                "href_matches": "/*"
            },
            "eagerness": "moderate"
        }]
    }
</script>
```

#### Logs taken while reproducing problem

![screenshot_2024-10-04_at_4 31 58___pm](https://github.com/user-attachments/assets/0bcb986b-bfc2-4625-8917-1352b0c20d19)

**Comment by trieloff** [comment]
This is a reporting issue, not a data collection issue.

**Comment by kptdobe** [comment]
After looking at the data and re-thinking about it, I agree with @trieloff. I have revert the commit for now.

**Comment by ramboz** [comment]
Doing it in the reporting works for me as well. It is a bit more tricky for non-experts though, as pageviews will be inflated, which impacts all CTR/CVR calculations. So, if we do it only in the reporting, we have to make sure to inform all consumers of the APIs

**Comment by ramboz** [comment]
How would you handle it in the RUM explorer?
Would we just leave it as-is and expect users to properly filter with `target=visible`? Or would we filter out what is `target=hidden` by default, and give the option to bring them back in if needed?

**Comment by trieloff** [comment]
Loading pages in non-active tabs is quite common, especially when navigating from listing pages to details.

**Comment by kptdobe** [comment]
Hard to believe... this is an advanced usage of the browser, majority of the people can only deal with one tab. To be validated with data ;)

**Comment by trieloff** [comment]
One of the main drivers for me to integrate this was a presentation by one of the RUM guys at Akamai who said that background opens are frequent enough to distort CWV values.

**Comment by kptdobe** [comment]
Just found out that a `reload` is currently triggered when navigating to a pre-rendered page.

**Comment by kptdobe** [comment]
Fixed with the several linked PRs.
